language: python

sudo: false

env:
  - TOX_ENV=py27-django15-drf2
  - TOX_ENV=py27-django15-drf3
  - TOX_ENV=py27-django15-drf31
  - TOX_ENV=py27-django16-drf2
  - TOX_ENV=py27-django16-drf3
  - TOX_ENV=py27-django16-drf31
  - TOX_ENV=py27-django17-drf2
  - TOX_ENV=py27-django17-drf3
  - TOX_ENV=py27-django17-drf31
  - TOX_ENV=py27-django18-drf2
  - TOX_ENV=py27-django18-drf3
  - TOX_ENV=py27-django18-drf31
  - TOX_ENV=py34-django15-drf2
  - TOX_ENV=py34-django15-drf3
  - TOX_ENV=py34-django15-drf31
  - TOX_ENV=py34-django16-drf2
  - TOX_ENV=py34-django16-drf3
  - TOX_ENV=py34-django16-drf31
  - TOX_ENV=py34-django17-drf2
  - TOX_ENV=py34-django17-drf3
  - TOX_ENV=py34-django17-drf31
  - TOX_ENV=py34-django18-drf2
  - TOX_ENV=py34-django18-drf3
  - TOX_ENV=py34-django18-drf31

install:
  - make requirements

before_script:
  - pip install python-coveralls

script:
    - tox -e $TOX_ENV

after_success:
  - coveralls
